export interface CountryRider {
  id: string;
  flag: string;
  country: string;
  displayName: string;
  multiplier: number;
  winAmount: number;
  coin: string;
  isLive?: boolean;
  timestamp: number;
}

export const initial100Riders: CountryRider[] = [
  { id: "tr1-in", flag: "🇮🇳", country: "India", displayName: "Rider_Raj", multiplier: 15.40, winAmount: 450000, coin: "INR", timestamp: Date.now() - 360000 },
  { id: "tr1-us", flag: "🇺🇸", country: "United States", displayName: "Crypto_King", multiplier: 24.50, winAmount: 12450, coin: "USDT", timestamp: Date.now() - 480000 },
  { id: "tr1-br", flag: "🇧🇷", country: "Brazil", displayName: "Silva_Fast", multiplier: 18.20, winAmount: 89000, coin: "BRL", timestamp: Date.now() - 540000 },
  { id: "tr1-uk", flag: "🇬🇧", country: "United Kingdom", displayName: "London_Flyer", multiplier: 12.80, winAmount: 9200, coin: "USDT", timestamp: Date.now() - 600000 },
  { id: "tr1-ru", flag: "🇷🇺", country: "Russia", displayName: "Vortex_RU", multiplier: 45.30, winAmount: 950500, coin: "RUB", timestamp: Date.now() - 720000 },
  { id: "tr1-de", flag: "🇩🇪", country: "Germany", displayName: "Blitz_Rider", multiplier: 32.10, winAmount: 11400, coin: "EUR", timestamp: Date.now() - 840000 },
  { id: "tr1-za", flag: "🇿🇦", country: "South Africa", displayName: "Zulu_Force", multiplier: 9.80, winAmount: 180000, coin: "ZAR", timestamp: Date.now() - 900000 },
  { id: "tr1-ae", flag: "🇦🇪", country: "U.A.E", displayName: "Habibi_Ride", multiplier: 55.00, winAmount: 45000, coin: "AED", timestamp: Date.now() - 1020000 },
  { id: "tr1-ca", flag: "🇨🇦", country: "Canada", displayName: "Maple_Speed", multiplier: 14.60, winAmount: 14800, coin: "CAD", timestamp: Date.now() - 1100000 },
  { id: "tr1-au", flag: "🇦🇺", country: "Australia", displayName: "Oz_Bullet", multiplier: 19.30, winAmount: 13500, coin: "AUD", timestamp: Date.now() - 1200000 },
  { id: "tr1-jp", flag: "🇯🇵", country: "Japan", displayName: "Zen_Rider", multiplier: 88.40, winAmount: 1850000, coin: "JPY", timestamp: Date.now() - 1300000 },
  { id: "tr1-fr", flag: "🇫🇷", country: "France", displayName: "Veloce_FR", multiplier: 11.50, winAmount: 8900, coin: "EUR", timestamp: Date.now() - 1400000 },
  { id: "tr1-es", flag: "🇪🇸", country: "Spain", displayName: "El_Toro", multiplier: 16.20, winAmount: 7200, coin: "EUR", timestamp: Date.now() - 1500000 },
  { id: "tr1-sa", flag: "🇸🇦", country: "Saudi Arabia", displayName: "Desert_Storm", multiplier: 38.50, winAmount: 38000, coin: "SAR", timestamp: Date.now() - 1600000 },
  { id: "tr1-tr", flag: "🇹🇷", country: "Turkey", displayName: "Anatolia_Speed", multiplier: 27.60, winAmount: 280000, coin: "TRY", timestamp: Date.now() - 1700000 },
  { id: "tr1-it", flag: "🇮🇹", country: "Italy", displayName: "Corsa_Rider", multiplier: 21.40, winAmount: 9100, coin: "EUR", timestamp: Date.now() - 1800000 },
  { id: "tr1-mx", flag: "🇲🇽", country: "Mexico", displayName: "El_Patron", multiplier: 19.90, winAmount: 240000, coin: "MXN", timestamp: Date.now() - 1900000 },
  { id: "tr1-sg", flag: "🇸🇬", country: "Singapore", displayName: "Merlion_Rider", multiplier: 42.10, winAmount: 16400, coin: "SGD", timestamp: Date.now() - 2000000 },
  { id: "tr1-my", flag: "🇲🇾", country: "Malaysia", displayName: "KL_Force", multiplier: 13.50, winAmount: 45500, coin: "MYR", timestamp: Date.now() - 2100000 },
  { id: "tr1-id", flag: "🇮🇩", country: "Indonesia", displayName: "Bali_Dream", multiplier: 16.80, winAmount: 180000000, coin: "IDR", timestamp: Date.now() - 2200000 },
  { id: "tr1-nl", flag: "🇳🇱", country: "Netherlands", displayName: "Oranje_Rider", multiplier: 14.20, winAmount: 8400, coin: "EUR", timestamp: Date.now() - 2300000 },
  { id: "tr1-ar", flag: "🇦🇷", country: "Argentina", displayName: "Messi_Fan", multiplier: 65.40, winAmount: 3500000, coin: "ARS", timestamp: Date.now() - 2400000 },
  { id: "tr1-co", flag: "🇨🇴", country: "Colombia", displayName: "Cafe_Speed", multiplier: 22.80, winAmount: 48000000, coin: "COP", timestamp: Date.now() - 2500000 },
  { id: "tr1-kr", flag: "🇰🇷", country: "South Korea", displayName: "K_Rider", multiplier: 33.20, winAmount: 17500000, coin: "KRW", timestamp: Date.now() - 2600000 },
  { id: "tr1-ph", flag: "🇵🇭", country: "Philippines", displayName: "Pinoy_Power", multiplier: 11.90, winAmount: 550000, coin: "PHP", timestamp: Date.now() - 2700000 },
  { id: "tr1-vn", flag: "🇻🇳", country: "Vietnam", displayName: "Dong_Speed", multiplier: 58.40, winAmount: 280000000, coin: "VND", timestamp: Date.now() - 2800000 },
  { id: "tr1-nz", flag: "🇳🇿", country: "New Zealand", displayName: "Kiwi_Rider", multiplier: 15.60, winAmount: 15600, coin: "NZD", timestamp: Date.now() - 2900000 },
  { id: "tr1-ch", flag: "🇨🇭", country: "Switzerland", displayName: "Alpine_Flyer", multiplier: 22.20, winAmount: 12200, coin: "CHF", timestamp: Date.now() - 3000000 },
  { id: "tr1-se", flag: "🇸🇪", country: "Sweden", displayName: "Svea_Fast", multiplier: 17.50, winAmount: 120500, coin: "SEK", timestamp: Date.now() - 3100000 },
  { id: "tr1-no", flag: "🇳🇴", country: "Norway", displayName: "Fjord_Rider", multiplier: 13.00, winAmount: 135000, coin: "NOK", timestamp: Date.now() - 3200000 },
  { id: "tr1-dk", flag: "🇩🇰", country: "Denmark", displayName: "Dannebrog", multiplier: 18.40, winAmount: 88400, coin: "DKK", timestamp: Date.now() - 3300000 },
  { id: "tr1-pl", flag: "🇵🇱", country: "Poland", displayName: "Winged_Hussar", multiplier: 14.50, winAmount: 44500, coin: "PLN", timestamp: Date.now() - 3400000 },
  { id: "tr1-ua", flag: "🇺🇦", country: "Ukraine", displayName: "Cossack_Speed", multiplier: 32.00, winAmount: 320000, coin: "UAH", timestamp: Date.now() - 3500000 },
  { id: "tr1-eg", flag: "🇪🇬", country: "Egypt", displayName: "Pharaoh_Ride", multiplier: 25.00, winAmount: 145000, coin: "EGP", timestamp: Date.now() - 3600000 },
  { id: "tr1-ng", flag: "🇳🇬", country: "Nigeria", displayName: "Naija_Rider", multiplier: 75.00, winAmount: 12500000, coin: "NGN", timestamp: Date.now() - 3700000 },
  { id: "tr1-ke", flag: "🇰🇪", country: "Kenya", displayName: "Safari_Fast", multiplier: 11.45, winAmount: 1450000, coin: "KES", timestamp: Date.now() - 3800000 },
  { id: "tr1-il", flag: "🇮🇱", country: "Israel", displayName: "Shalom_Ride", multiplier: 14.20, winAmount: 42000, coin: "ILS", timestamp: Date.now() - 3900000 },
  { id: "tr1-ir", flag: "🇮🇷", country: "Iran", displayName: "Persian_Cat", multiplier: 45.00, winAmount: 450000000, coin: "IRR", timestamp: Date.now() - 4000000 },
  { id: "tr1-cl", flag: "🇨🇱", country: "Chile", displayName: "Andean_Flyer", multiplier: 19.50, winAmount: 9500000, coin: "CLP", timestamp: Date.now() - 4100000 },
  { id: "tr1-pe", flag: "🇵🇪", country: "Peru", displayName: "Inca_Rider", multiplier: 13.80, winAmount: 38000, coin: "PEN", timestamp: Date.now() - 4200000 },
  { id: "tr1-pt", flag: "🇵🇹", country: "Portugal", displayName: "Ronaldo_CR7", multiplier: 16.80, winAmount: 6800, coin: "EUR", timestamp: Date.now() - 4300000 },
  { id: "tr1-be", flag: "🇧🇪", country: "Belgium", displayName: "Waffle_Rider", multiplier: 17.50, winAmount: 7500, coin: "EUR", timestamp: Date.now() - 4400000 },
  { id: "tr1-at", flag: "🇦🇹", country: "Austria", displayName: "Vienna_Speed", multiplier: 18.20, winAmount: 8200, coin: "EUR", timestamp: Date.now() - 4500000 },
  { id: "tr1-gr", flag: "🇬🇷", country: "Greece", displayName: "Spartan_Rider", multiplier: 15.90, winAmount: 5900, coin: "EUR", timestamp: Date.now() - 4600000 },
  { id: "tr1-ie", flag: "🇮🇪", country: "Ireland", displayName: "Leprechaun", multiplier: 19.40, winAmount: 9400, coin: "EUR", timestamp: Date.now() - 4700000 },
  { id: "tr1-fi", flag: "🇫🇮", country: "Finland", displayName: "Sisu_Fast", multiplier: 10.20, winAmount: 10200, coin: "EUR", timestamp: Date.now() - 4800000 },
  { id: "tr1-ro", flag: "🇷🇴", country: "Romania", displayName: "Dracula_Speed", multiplier: 13.80, winAmount: 38000, coin: "RON", timestamp: Date.now() - 4900000 },
  { id: "tr1-hu", flag: "🇭🇺", country: "Hungary", displayName: "Magyar_Rider", multiplier: 12.80, winAmount: 2800000, coin: "HUF", timestamp: Date.now() - 5000000 },
  { id: "tr1-cz", flag: "🇨🇿", country: "Czechia", displayName: "Prague_Speed", multiplier: 23.00, winAmount: 230000, coin: "CZK", timestamp: Date.now() - 5100000 },
  { id: "tr1-bg", flag: "🇧🇬", country: "Bulgaria", displayName: "Sofia_Fast", multiplier: 14.00, winAmount: 14000, coin: "BGN", timestamp: Date.now() - 5200000 },
  { id: "tr1-hr", flag: "🇭🇷", country: "Croatia", displayName: "Adriatic_Rider", multiplier: 17.80, winAmount: 7800, coin: "EUR", timestamp: Date.now() - 5300000 },
  { id: "tr1-si", flag: "🇸🇮", country: "Slovenia", displayName: "Triglav_Speed", multiplier: 16.50, winAmount: 6500, coin: "EUR", timestamp: Date.now() - 5400000 },
  { id: "tr1-sk", flag: "🇸🇰", country: "Slovakia", displayName: "Tatra_Rider", multiplier: 16.90, winAmount: 6900, coin: "EUR", timestamp: Date.now() - 5500000 },
  { id: "tr1-lt", flag: "🇱🇹", country: "Lithuania", displayName: "Vytis_Speed", multiplier: 15.80, winAmount: 5800, coin: "EUR", timestamp: Date.now() - 5600000 },
  { id: "tr1-lv", flag: "🇱🇻", country: "Latvia", displayName: "Riga_Rider", multiplier: 14.90, winAmount: 4900, coin: "EUR", timestamp: Date.now() - 5700000 },
  { id: "tr1-ee", flag: "🇪🇪", country: "Estonia", displayName: "Tallinn_Rider", multiplier: 17.10, winAmount: 7100, coin: "EUR", timestamp: Date.now() - 5800000 },
  { id: "tr1-is", flag: "🇮🇸", country: "Iceland", displayName: "Geyser_Speed", multiplier: 19.80, winAmount: 980000, coin: "ISK", timestamp: Date.now() - 5900000 },
  { id: "tr1-mt", flag: "🇲🇹", country: "Malta", displayName: "Valletta_Rider", multiplier: 21.50, winAmount: 11500, coin: "EUR", timestamp: Date.now() - 6000000 },
  { id: "tr1-cy", flag: "🇨🇾", country: "Cyprus", displayName: "Aphrodite", multiplier: 18.10, winAmount: 8100, coin: "EUR", timestamp: Date.now() - 6100000 },
  { id: "tr1-lu", flag: "🇱🇺", country: "Luxembourg", displayName: "Luxe_Rider", multiplier: 18.40, winAmount: 18400, coin: "EUR", timestamp: Date.now() - 6200000 },
  { id: "tr1-cn", flag: "🇨🇳", country: "China", displayName: "Dragon_Rider", multiplier: 38.50, winAmount: 98500, coin: "CNY", timestamp: Date.now() - 6300000 },
  { id: "tr1-hk", flag: "🇭🇰", country: "Hong Kong", displayName: "HK_Traders", multiplier: 15.00, winAmount: 115000, coin: "HKD", timestamp: Date.now() - 6400000 },
  { id: "tr1-tw", flag: "🇹🇼", country: "Taiwan", displayName: "Formosa_Speed", multiplier: 25.00, winAmount: 450000, coin: "TWD", timestamp: Date.now() - 6500000 },
  { id: "tr1-th", flag: "🇹🇭", country: "Thailand", displayName: "Siam_Rider", multiplier: 18.00, winAmount: 380000, coin: "THB", timestamp: Date.now() - 6600000 },
  { id: "tr1-bd", flag: "🇧🇩", country: "Bangladesh", displayName: "Bengal_Tiger", multiplier: 15.50, winAmount: 550000, coin: "BDT", timestamp: Date.now() - 6700000 },
  { id: "tr1-pk", flag: "🇵🇰", country: "Pakistan", displayName: "Lahore_Speed", multiplier: 12.00, winAmount: 1200000, coin: "PKR", timestamp: Date.now() - 6800000 },
  { id: "tr1-lk", flag: "🇱🇰", country: "Sri Lanka", displayName: "Lanka_Flyer", multiplier: 18.00, winAmount: 1800000, coin: "LKR", timestamp: Date.now() - 6900000 },
  { id: "tr1-np", flag: "🇳🇵", country: "Nepal", displayName: "Himalaya_Rider", multiplier: 14.80, winAmount: 480000, coin: "NPR", timestamp: Date.now() - 7000000 },
  { id: "tr1-qa", flag: "🇶🇦", country: "Qatar", displayName: "Doha_Trader", multiplier: 15.00, winAmount: 45000, coin: "QAR", timestamp: Date.now() - 7100000 },
  { id: "tr1-kw", flag: "🇰🇼", country: "Kuwait", displayName: "KWT_HighRoller", multiplier: 13.80, winAmount: 3800, coin: "KWD", timestamp: Date.now() - 7200000 },
  { id: "tr1-om", flag: "🇴🇲", country: "Oman", displayName: "Muscat_Rider", multiplier: 15.20, winAmount: 5200, coin: "OMR", timestamp: Date.now() - 7300000 },
  { id: "tr1-bh", flag: "🇧🇭", country: "Bahrain", displayName: "Manama_Speed", multiplier: 14.90, winAmount: 4900, coin: "BHD", timestamp: Date.now() - 7400000 },
  { id: "tr1-jo", flag: "🇯🇴", country: "Jordan", displayName: "Petra_Rider", multiplier: 19.50, winAmount: 9500, coin: "JOD", timestamp: Date.now() - 7500000 },
  { id: "tr1-lb", flag: "🇱🇧", country: "Lebanon", displayName: "Cedar_Speed", multiplier: 17.50, winAmount: 750000000, coin: "LBP", timestamp: Date.now() - 7600000 },
  { id: "tr1-kz", flag: "🇰🇿", country: "Kazakhstan", displayName: "Steppe_Rider", multiplier: 15.00, winAmount: 2800000, coin: "KZT", timestamp: Date.now() - 7700000 },
  { id: "tr1-uz", flag: "🇺🇿", country: "Uzbekistan", displayName: "Tashkent_Speed", multiplier: 14.00, winAmount: 65000000, coin: "UZS", timestamp: Date.now() - 7800000 },
  { id: "tr1-mn", flag: "🇲🇳", country: "Mongolia", displayName: "Nomad_Rider", multiplier: 17.50, winAmount: 17500000, coin: "MNT", timestamp: Date.now() - 7900000 },
  { id: "tr1-jm", flag: "🇯🇲", country: "Jamaica", displayName: "Bolt_Fan", multiplier: 18.50, winAmount: 850000, coin: "JMD", timestamp: Date.now() - 8000000 },
  { id: "tr1-cr", flag: "🇨🇷", country: "Costa Rica", displayName: "Pura_Vida", multiplier: 12.80, winAmount: 2800022, coin: "CRC", timestamp: Date.now() - 8100000 },
  { id: "tr1-pa", flag: "🇵🇦", country: "Panama", displayName: "Canal_Rider", multiplier: 11.50, winAmount: 11500, coin: "USD", timestamp: Date.now() - 8200000 },
  { id: "tr1-do", flag: "🇩🇴", country: "Dominican Rep.", displayName: "Santo_Dom", multiplier: 18.00, winAmount: 280000, coin: "DOP", timestamp: Date.now() - 8300000 },
  { id: "tr1-ec", flag: "🇪🇨", country: "Ecuador", displayName: "Quito_Speed", multiplier: 16.90, winAmount: 6900, coin: "USD", timestamp: Date.now() - 8400000 },
  { id: "tr1-ve", flag: "🇻🇪", country: "Venezuela", displayName: "Bolivar_Fast", multiplier: 25.00, winAmount: 250000, coin: "VES", timestamp: Date.now() - 8500000 },
  { id: "tr1-uy", flag: "🇺🇾", country: "Uruguay", displayName: "Celeste_Rider", multiplier: 12.00, winAmount: 320000, coin: "UYU", timestamp: Date.now() - 8600000 },
  { id: "tr1-py", flag: "🇵🇾", country: "Paraguay", displayName: "Guarani_Speed", multiplier: 15.00, winAmount: 45000000, coin: "PYG", timestamp: Date.now() - 8700000 },
  { id: "tr1-bo", flag: "🇧🇴", country: "Bolivia", displayName: "Andes_Rider", multiplier: 14.80, winAmount: 48000, coin: "BOB", timestamp: Date.now() - 8800000 },
  { id: "tr1-gt", flag: "🇬🇹", country: "Guatemala", displayName: "Quetzal_Rider", multiplier: 15.50, winAmount: 55000, coin: "GTQ", timestamp: Date.now() - 8900000 },
  { id: "tr1-hn", flag: "🇭🇳", country: "Honduras", displayName: "Lempira", multiplier: 14.50, winAmount: 145000, coin: "HNL", timestamp: Date.now() - 9000000 },
  { id: "tr1-sv", flag: "🇸🇻", country: "El Salvador", displayName: "Bitcoin_Rider", multiplier: 18.20, winAmount: 8200, coin: "USD", timestamp: Date.now() - 9100000 },
  { id: "tr1-ni", flag: "🇳🇮", country: "Nicaragua", displayName: "Volcano_Speed", multiplier: 12.00, winAmount: 220000, coin: "NIO", timestamp: Date.now() - 9200000 },
  { id: "tr1-ma", flag: "🇲🇦", country: "Morocco", displayName: "Atlas_Lion", multiplier: 18.00, winAmount: 48000, coin: "MAD", timestamp: Date.now() - 9300000 },
  { id: "tr1-dz", flag: "🇩🇿", country: "Algeria", displayName: "Sahara_Rider", multiplier: 15.00, winAmount: 650000, coin: "DZD", timestamp: Date.now() - 9400000 },
  { id: "tr1-tn", flag: "🇹🇳", country: "Tunisia", displayName: "Carthage_Speed", multiplier: 15.00, winAmount: 15000, coin: "TND", timestamp: Date.now() - 9500000 },
  { id: "tr1-gh", flag: "🇬🇭", country: "Ghana", displayName: "Black_Star", multiplier: 15.00, winAmount: 95000, coin: "GHS", timestamp: Date.now() - 9600000 },
  { id: "tr1-ci", flag: "🇨🇮", country: "Cote d'Ivoire", displayName: "Cote_Speed", multiplier: 18.00, winAmount: 4800000, coin: "XOF", timestamp: Date.now() - 9700000 },
  { id: "tr1-cm", flag: "🇨🇲", country: "Cameroon", displayName: "Lion_Force", multiplier: 15.00, winAmount: 3900000, coin: "XAF", timestamp: Date.now() - 9800000 },
  { id: "tr1-sn", flag: "🇸🇳", country: "Senegal", displayName: "Dakar_Fast", multiplier: 18.00, winAmount: 4200000, coin: "XOF", timestamp: Date.now() - 9900000 },
  { id: "tr1-ao", flag: "🇦🇴", country: "Angola", displayName: "Luanda_Speed", multiplier: 15.00, winAmount: 3500000, coin: "AOA", timestamp: Date.now() - 10000000 },
  { id: "tr1-et", flag: "🇪🇹", country: "Ethiopia", displayName: "Abyssinia_Rider", multiplier: 18.00, winAmount: 480000, coin: "ETB", timestamp: Date.now() - 10100000 },
  { id: "tr1-fj", flag: "🇫🇯", country: "Fiji", displayName: "Pacific_Wave", multiplier: 12.50, winAmount: 12500, coin: "FJD", timestamp: Date.now() - 10200000 }
];

export const allCountriesWithFlags = [
  { flag: "🇮🇳", country: "India", coin: "INR", displayPrefix: "₹" },
  { flag: "🇺🇸", country: "United States", coin: "USDT", displayPrefix: "$" },
  { flag: "🇧🇷", country: "Brazil", coin: "BRL", displayPrefix: "R$" },
  { flag: "🇬🇧", country: "United Kingdom", coin: "USDT", displayPrefix: "£" },
  { flag: "🇷🇺", country: "Russia", coin: "RUB", displayPrefix: "₽" },
  { flag: "🇩🇪", country: "Germany", coin: "EUR", displayPrefix: "€" },
  { flag: "🇿🇦", country: "South Africa", coin: "ZAR", displayPrefix: "R" },
  { flag: "🇦🇪", country: "U.A.E", coin: "AED", displayPrefix: "AED " },
  { flag: "🇨🇦", country: "Canada", coin: "CAD", displayPrefix: "C$" },
  { flag: "🇦🇺", country: "Australia", coin: "AUD", displayPrefix: "A$" },
  { flag: "🇯🇵", country: "Japan", coin: "JPY", displayPrefix: "¥" },
  { flag: "🇫🇷", country: "France", coin: "EUR", displayPrefix: "€" },
  { flag: "🇪🇸", country: "Spain", coin: "EUR", displayPrefix: "€" },
  { flag: "🇸🇦", country: "Saudi Arabia", coin: "SAR", displayPrefix: "SAR " },
  { flag: "🇹🇷", country: "Turkey", coin: "TRY", displayPrefix: "₺" },
  { flag: "🇮🇹", country: "Italy", coin: "EUR", displayPrefix: "€" },
  { flag: "🇲🇽", country: "Mexico", coin: "MXN", displayPrefix: "MXN $" },
  { flag: "🇸🇬", country: "Singapore", coin: "SGD", displayPrefix: "S$" },
  { flag: "🇲🇾", country: "Malaysia", coin: "MYR", displayPrefix: "RM" },
  { flag: "🇮🇩", country: "Indonesia", coin: "IDR", displayPrefix: "Rp" },
  { flag: "🇳🇱", country: "Netherlands", coin: "EUR", displayPrefix: "€" },
  { flag: "🇦🇷", country: "Argentina", coin: "ARS", displayPrefix: "ARS $" },
  { flag: "🇨🇴", country: "Colombia", coin: "COP", displayPrefix: "COP $" },
  { flag: "🇰🇷", country: "South Korea", coin: "KRW", displayPrefix: "₩" },
  { flag: "🇵🇭", country: "Philippines", coin: "PHP", displayPrefix: "₱" },
  { flag: "🇻🇳", country: "Vietnam", coin: "VND", displayPrefix: "₫" },
  { flag: "🇳🇿", country: "New Zealand", coin: "NZD", displayPrefix: "NZ$" },
  { flag: "🇨🇭", country: "Switzerland", coin: "CHF", displayPrefix: "CHF " },
  { flag: "🇸🇪", country: "Sweden", coin: "SEK", displayPrefix: "kr" },
  { flag: "🇳🇴", country: "Norway", coin: "NOK", displayPrefix: "kr" },
  { flag: "🇩🇰", country: "Denmark", coin: "DKK", displayPrefix: "kr" },
  { flag: "🇵🇱", country: "Poland", coin: "PLN", displayPrefix: "zł" },
  { flag: "🇺🇦", country: "Ukraine", coin: "UAH", displayPrefix: "₴" },
  { flag: "🇪🇬", country: "Egypt", coin: "EGP", displayPrefix: "EGP " },
  { flag: "🇳🇬", country: "Nigeria", coin: "NGN", displayPrefix: "₦" },
  { flag: "🇰🇪", country: "Kenya", coin: "KES", displayPrefix: "KSh " },
  { flag: "🇮🇸", country: "Iceland", coin: "ISK", displayPrefix: "kr" },
  { flag: "🇨🇳", country: "China", coin: "CNY", displayPrefix: "¥" },
  { flag: "🇭🇰", country: "Hong Kong", coin: "HKD", displayPrefix: "HK$" },
  { flag: "🇹🇼", country: "Taiwan", coin: "TWD", displayPrefix: "NT$" },
  { flag: "🇹🇭", country: "Thailand", coin: "THB", displayPrefix: "฿" },
  { flag: "🇧🇩", country: "Bangladesh", coin: "BDT", displayPrefix: "৳" },
  { flag: "🇵🇰", country: "Pakistan", coin: "PKR", displayPrefix: "₨" },
  { flag: "🇳🇵", country: "Nepal", coin: "NPR", displayPrefix: "₨" },
  { flag: "🇶🇦", country: "Qatar", coin: "QAR", displayPrefix: "QAR " },
  { flag: "🇰🇼", country: "Kuwait", coin: "KWD", displayPrefix: "KWD " },
  { flag: "🇴🇲", country: "Oman", coin: "OMR", displayPrefix: "OMR " },
  { flag: "🇧🇭", country: "Bahrain", coin: "BHD", displayPrefix: "BHD " },
  { flag: "🇯🇴", country: "Jordan", coin: "JOD", displayPrefix: "JOD " },
  { flag: "🇱🇧", country: "Lebanon", coin: "LBP", displayPrefix: "LBP " },
  { flag: "🇰🇿", country: "Kazakhstan", coin: "KZT", displayPrefix: "₸" },
  { flag: "🇺🇿", country: "Uzbekistan", coin: "UZS", displayPrefix: "som " },
  { flag: "🇲🇳", country: "Mongolia", coin: "MNT", displayPrefix: "₮" },
  { flag: "🇯🇲", country: "Jamaica", coin: "JMD", displayPrefix: "J$" },
  { flag: "🇨🇷", country: "Costa Rica", coin: "CRC", displayPrefix: "₡" },
  { flag: "🇵🇦", country: "Panama", coin: "USD", displayPrefix: "$" },
  { flag: "🇩🇴", country: "Dominican Rep.", coin: "DOP", displayPrefix: "RD$" },
  { flag: "🇪🇨", country: "Ecuador", coin: "USD", displayPrefix: "$" },
  { flag: "🇻🇪", country: "Venezuela", coin: "VES", displayPrefix: "Bs.S " },
  { flag: "🇺🇾", country: "Uruguay", coin: "UYU", displayPrefix: "$U " },
  { flag: "🇵🇾", country: "Paraguay", coin: "PYG", displayPrefix: "₲" },
  { flag: "🇧🇴", country: "Bolivia", coin: "BOB", displayPrefix: "Bs " },
  { flag: "🇬🇹", country: "Guatemala", coin: "GTQ", displayPrefix: "Q" },
  { flag: "🇭🇳", country: "Honduras", coin: "HNL", displayPrefix: "L" },
  { flag: "🇸🇻", country: "El Salvador", coin: "USD", displayPrefix: "$" },
  { flag: "🇳🇮", country: "Nicaragua", coin: "NIO", displayPrefix: "C$" },
  { flag: "🇲🇦", country: "Morocco", coin: "MAD", displayPrefix: "DH " },
  { flag: "🇩🇿", country: "Algeria", coin: "DZD", displayPrefix: "DA " },
  { flag: "🇹🇳", country: "Tunisia", coin: "TND", displayPrefix: "DT " },
  { flag: "🇬🇭", country: "Ghana", coin: "GHS", displayPrefix: "GH₵ " },
  { flag: "🇨🇮", country: "Cote d'Ivoire", coin: "XOF", displayPrefix: "CFA " },
  { flag: "🇨🇲", country: "Cameroon", coin: "XAF", displayPrefix: "CFA " },
  { flag: "🇸🇳", country: "Senegal", coin: "XOF", displayPrefix: "CFA " },
  { flag: "🇦🇴", country: "Angola", coin: "AOA", displayPrefix: "Kz " },
  { flag: "🇪🇹", country: "Ethiopia", coin: "ETB", displayPrefix: "ETB " },
  { flag: "🇫🇯", country: "Fiji", coin: "FJD", displayPrefix: "FJD " }
];

export const allFirstNames = [
  "Abhishek", "Aarav", "Rohan", "Siddharth", "Vikram", "Thiago", "Mateo", "Alex", "Max", "Hans",
  "John", "Mike", "David", "Lucas", "James", "Dmitry", "Sergey", "Kenji", "Hiro", "Yuki",
  "Sven", "Lars", "Finn", "Oliver", "Noah", "Elena", "Sophia", "Camila", "Isabella", "Emma",
  "Ravi", "Amit", "Karan", "Sanjay", "Anil", "Jose", "Carlos", "Luis", "Miguel", "Pedro",
  "Jean", "Pierre", "Antoine", "Guillaume", "Diego", "Mateo", "Leo", "Bastian", "Ali", "Mustafa",
  "Ahmed", "Habibi", "Youssef", "Omar", "Tariq", "Zayd", "Kwame", "Kofi", "Chinedu", "Tunde",
  "Nils", "Gustav", "Pavel", "Ivan", "Jan", "Tomasz", "Andrzej", "Stefan", "Luka", "Andrej",
  "Tariq", "Rajesh", "Prakash", "Vijay", "Ajay", "Harish", "Rahul", "Pranav", "Sai", "Krishna",
  "Somchai", "Kia", "Nguyen", "Minh", "Tan", "Wee", "Teck", "Chen", "Wei", "Hao", "Chao"
];

export const allLastNameSuffixes = [
  "_Rider", "_Bullet", "_Speed", "_Turbo", "_Fast", "_Nailer", "_HighRoller", "_SkyWalker", "_Rider350",
  "_God", "_Lord", "_Machine", "_Master", "_Pro", "_Whale", "_Boss", "_Champ", "_King", "_Elite", "_Winner"
];
